/*CUSTOMERS*/
export const GET_ALL_CUSTOMERS_REQUEST = 'GET_ALL_CUSTOMERS_REQUEST';
export const GET_ALL_CUSTOMERS_ERROR = 'GET_ALL_CUSTOMERS_ERROR';
export const GET_ALL_CUSTOMERS_SUCCESS = 'GET_ALL_CUSTOMERS_SUCCESS';

export const PUT_CUSTOMER_IDLE = 'PUT_CUSTOMER_IDLE';
export const PUT_CUSTOMER_REQUEST = 'PUT_CUSTOMERS_REQUEST';
export const PUT_CUSTOMER_ERROR = 'PUT_CUSTOMERS_ERROR';
export const PUT_CUSTOMER_SUCCESS = 'PUT_CUSTOMERS_SUCCESS';

export const POST_CUSTOMER_IDLE = 'POST_CUSTOMER_IDLE';
export const POST_CUSTOMER_REQUEST = 'POST_CUSTOMER_REQUEST';
export const POST_CUSTOMER_ERROR = 'POST_CUSTOMER_ERROR';
export const POST_CUSTOMER_SUCCESS = 'POST_CUSTOMER_SUCCESS';

/*BILLING*/
export const GET_ALL_USAGE_REQUEST = 'GET_ALL_USAGE_REQUEST';
export const GET_ALL_USAGE_ERROR = 'GET_ALL_USAGE_ERROR';
export const GET_ALL_USAGE_SUCCESS = 'GET_ALL_USAGE_SUCCESS';
/*SERVICE MONITOR*/
export const GET_ALL_SERVICE_LOCATIONS_REQUEST = 'GET_ALL_SERVICE_LOCATIONS_REQUEST';
export const GET_ALL_SERVICE_LOCATIONS_ERROR = 'GET_ALL_SERVICE_LOCATIONS_ERROR';
export const GET_ALL_SERVICE_LOCATIONS_SUCCESS = 'GET_ALL_SERVICE_LOCATIONS_SUCCESS';

export const PUT_SERVICE_LOCATION_IDLE = 'PUT_SERVICE_LOCATION_IDLE';
export const PUT_SERVICE_LOCATION_REQUEST = 'PUT_SERVICE_LOCATION_REQUEST';
export const PUT_SERVICE_LOCATION_ERROR = 'PUT_SERVICE_LOCATION_ERROR';
export const PUT_SERVICE_LOCATION_SUCCESS = 'PUT_SERVICE_LOCATION_SUCCESS';
/*INCOMPLETE TASKS*/
export const GET_ALL_INCOMPLETE_TASKS_REQUEST = 'GET_ALL_INCOMPLETE_TASKS_REQUEST';
export const GET_ALL_INCOMPLETE_TASKS_ERROR = 'GET_ALL_INCOMPLETE_TASKS_ERROR';
export const GET_ALL_INCOMPLETE_TASKS_SUCCESS = 'GET_ALL_INCOMPLETE_TASKS_SUCCESS';

export const DELETE_INCOMPLETE_TASK_IDLE = 'DELETE_INCOMPLETE_TASK_IDLE';
export const DELETE_INCOMPLETE_TASK_REQUEST = 'DELETE_INCOMPLETE_TASK_REQUEST';
export const DELETE_INCOMPLETE_TASK_ERROR = 'DELETE_INCOMPLETE_TASK_ERROR';
export const DELETE_INCOMPLETE_TASK_SUCCESS = 'DELETE_INCOMPLETE_TASK_SUCCESS';

export const POST_INCOMPLETE_TASK_IDLE = 'POST_INCOMPLETE_TASK_IDLE';
export const POST_INCOMPLETE_TASK_REQUEST = 'POST_INCOMPLETE_TASK_REQUEST';
export const POST_INCOMPLETE_TASK_ERROR = 'POST_INCOMPLETE_TASK_ERROR';
export const POST_INCOMPLETE_TASK_SUCCESS = 'POST_INCOMPLETE_TASK_SUCCESS';